### ISSUE TITLE
Python errors when running with Blender 3.4

### ISSUE THREAD

**Issue by tim-tim707** [louriccia/blender-swe1r#1]
I believe its a code error and not a Blender related issue.
It happens when trying to read Malt, Podd

```sh
Python: Traceback (most recent call last):
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\__init__.py", line 142, in execute
    import_model(folder_path, [int(context.scene.import_model)])
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\swe1r_import.py", line 1080, in import_model
    model = Model(id).read(modelblock)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 1519, in read
    cursor = self.header.read(buffer, cursor)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 1433, in read
    cursor = read_AltN(buffer, cursor + 4, model)
NameError: name 'read_AltN' is not defined
```

Here is another trace when trying to read 'Part':
```sh
Python: Traceback (most recent call last):
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\__init__.py", line 142, in execute
    import_model(folder_path, [int(context.scene.import_model)])
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\swe1r_import.py", line 1081, in import_model
    model.make()
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 1543, in make
    node.make()
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 1181, in make
    empty = super().make(parent)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 1109, in make
    node.make(new_empty)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 1147, in make
    return super().make(parent)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 1109, in make
    node.make(new_empty)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 934, in make
    self.visuals.make(parent)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 858, in make
    verts = [vert.pos for vert in self.vert_buffer.data]
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_swe1r\modelblock.py", line 858, in <listcomp>
    verts = [vert.pos for vert in self.vert_buffer.data]
AttributeError: 'VisualsVertChunk' object has no attribute 'pos'
```

Looks promising though !

**Comment by tim-tim707** [comment]
I personaly use Pylance VSCode extension that warns about undefined variables (If you are also on VSCode)
