### ISSUE TITLE
Readme link to release but there is no release yet

### ISSUE THREAD

**Issue by tim-tim707** [louriccia/blender-swe1r#10]
https://github.com/louriccia/blender-swe1r/releases -> no releases

The readme also talk about a .zip but there isn't one in the repository. I'm going to try to zip the repository (after git clone) and see if Blender accept it

**Comment by tim-tim707** [comment]
Error on blender 3.4 load Part Quad Power Cell:
```
Python: Traceback (most recent call last):
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\operators.py", line 58, in execute
    import_model(folder_path, [int(context.scene.import_model)])
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swr_import.py", line 87, in import_model
    collection = model.make()
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swe1r\modelblock.py", line 2908, in make
    node.make(None, collection)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swe1r\modelblock.py", line 2164, in make
    empty = super().make(parent, collection)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swe1r\modelblock.py", line 1998, in make
    node.make(new_node, collection)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swe1r\modelblock.py", line 2110, in make
    return super().make(parent, collection)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swe1r\modelblock.py", line 1998, in make
    node.make(new_node, collection)
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swe1r\modelblock.py", line 1522, in make
    mat = self.material.make()
  File "C:\Users\Tim\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-swe1r\swe1r\modelblock.py", line 1174, in make
    node_0.inputs["Specular IOR Level"].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular IOR Level" not found'
```

This makes me feel that I need to pre-process something ?
